name: Bug Report
description: Report a bug in LOBSTR Protocol
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug. Please fill out the details below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - contracts
        - web
        - indexer
        - circuits
        - agents
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to ...
        2. Run ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment info
      placeholder: |
        OS: macOS 15
        Node: 20.x
        Browser: Chrome 120
    validations:
      required: false
