name: Feature Request
description: Suggest a new feature for LOBSTR Protocol
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature. Please describe your idea below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - contracts
        - web
        - indexer
        - circuits
        - agents
        - other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you considered?
    validations:
      required: false
