import type { HumanProvider } from "./types";

// Seed providers — will be replaced by on-chain data from ServiceRegistry + StakingManager
export const MOCK_HUMANS: HumanProvider[] = [
  {
    id: "h1",
    name: "Marco Reyes",
    address: "0x4a91...c3E7",
    avatar: "MR",
    bio: "Licensed courier and logistics coordinator based in Austin. Specializing in same-day document delivery, package handling, and chain-of-custody transfers for legal and corporate clients.",
    skills: ["same-day delivery", "chain-of-custody", "logistics coordination"],
    categories: ["Errands & Delivery"],
    location: "Austin, TX",
    locationInfo: { city: "Austin", region: "Texas", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-6",
    hourlyRate: 35,
    flatRates: { "document delivery": 25, "package courier": 40 },
    availability: "available",
    responseTime: "< 15 min",
    completions: 47,
    rating: 4.9,
    reputationScore: 820,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1700000000000,
  },
  {
    id: "h2",
    name: "Natalia Voss",
    address: "0x7b3e...9F12",
    avatar: "NV",
    bio: "Mobile notary public and certified signing agent serving the greater New York area. Experienced with real estate closings, affidavits, power of attorney, and corporate filings.",
    skills: ["mobile notarization", "real estate closings", "corporate filings"],
    categories: ["Document & Legal"],
    location: "New York, NY",
    locationInfo: { city: "New York", region: "New York", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 120,
    flatRates: { "notarization session": 100, "real estate closing": 200 },
    availability: "available",
    responseTime: "< 30 min",
    completions: 93,
    rating: 5.0,
    reputationScore: 950,
    reputationTier: "Platinum",
    verified: true,
    joinedAt: 1695000000000,
  },
  {
    id: "h3",
    name: "James Adeyemi",
    address: "0x2d8f...5A04",
    avatar: "JA",
    bio: "Market research analyst conducting field surveys, competitive intelligence, and on-site data collection across London and the Southeast. Background in quantitative research methodology.",
    skills: ["field surveys", "competitive intelligence", "quantitative analysis"],
    categories: ["Field Research"],
    location: "London, UK",
    locationInfo: { city: "London", region: "England", country: "United Kingdom", countryCode: "GB", continent: "Europe" },
    timezone: "UTC+0",
    hourlyRate: 80,
    flatRates: { "site visit report": 60, "competitive analysis": 150 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 31,
    rating: 4.7,
    reputationScore: 680,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1702000000000,
  },
  {
    id: "h4",
    name: "Priya Kapoor",
    address: "0x6c4a...B821",
    avatar: "PK",
    bio: "Commercial product photographer with studio and on-location capability. Specializing in e-commerce catalog shoots, lifestyle imagery, and 360-degree product photography for digital platforms.",
    skills: ["product photography", "e-commerce imagery", "360-degree shoots"],
    categories: ["Photography & Video"],
    location: "Los Angeles, CA",
    locationInfo: { city: "Los Angeles", region: "California", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 150,
    flatRates: { "product shoot (10 items)": 200, "lifestyle session (half day)": 400 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 64,
    rating: 4.8,
    reputationScore: 780,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1698000000000,
  },
  {
    id: "h5",
    name: "Thomas Lin",
    address: "0x9e71...D463",
    avatar: "TL",
    bio: "IT infrastructure specialist handling server rack installations, structured cabling, access point deployment, and network commissioning for commercial and data center environments.",
    skills: ["server installation", "structured cabling", "network commissioning"],
    categories: ["Hardware & Setup"],
    location: "San Francisco, CA",
    locationInfo: { city: "San Francisco", region: "California", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 175,
    flatRates: { "rack build-out": 400, "network commissioning": 250 },
    availability: "busy",
    responseTime: "< 4 hr",
    completions: 28,
    rating: 4.9,
    reputationScore: 720,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1701000000000,
  },
  {
    id: "h6",
    name: "Claire Emerson",
    address: "0x3f82...7C95",
    avatar: "CE",
    bio: "Professional conference representative and executive assistant providing in-person meeting attendance, detailed note-taking, networking facilitation, and post-event reporting.",
    skills: ["conference representation", "executive assistance", "event reporting"],
    categories: ["Meetings & Events"],
    location: "Chicago, IL",
    locationInfo: { city: "Chicago", region: "Illinois", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-6",
    hourlyRate: 75,
    flatRates: { "full-day conference": 450, "meeting representation": 85 },
    availability: "available",
    responseTime: "< 30 min",
    completions: 52,
    rating: 4.6,
    reputationScore: 690,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1699000000000,
  },
  {
    id: "h7",
    name: "Diego Fuentes",
    address: "0x8a15...E2B7",
    avatar: "DF",
    bio: "Sensory evaluation specialist and food safety consultant. Conducting structured taste panels, product benchmarking, and quality assessment reports for F&B brands entering new markets.",
    skills: ["sensory evaluation", "product benchmarking", "quality assessment"],
    categories: ["Testing & QA"],
    location: "Miami, FL",
    locationInfo: { city: "Miami", region: "Florida", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 55,
    flatRates: { "taste panel session": 45, "benchmarking report": 80 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 38,
    rating: 4.5,
    reputationScore: 550,
    reputationTier: "Silver",
    verified: false,
    joinedAt: 1703000000000,
  },
  {
    id: "h8",
    name: "Yuki Hashimoto",
    address: "0x5d09...1F8A",
    avatar: "YH",
    bio: "Bilingual event coordinator and venue sourcing specialist in Tokyo. Providing location scouting, vendor negotiation, logistics planning, and cross-cultural liaison services for international clients.",
    skills: ["venue sourcing", "event logistics", "cross-cultural liaison"],
    categories: ["Meetings & Events", "Field Research"],
    location: "Tokyo, JP",
    locationInfo: { city: "Tokyo", region: "Kanto", country: "Japan", countryCode: "JP", continent: "Asia" },
    timezone: "UTC+9",
    hourlyRate: 65,
    flatRates: { "venue scouting (3 options)": 120, "event coordination": 200 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 21,
    rating: 4.8,
    reputationScore: 610,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1704000000000,
  },
  {
    id: "h9",
    name: "Elena Richter",
    address: "0x1c47...A6D0",
    avatar: "ER",
    bio: "Multilingual administrative services specialist in Berlin. Handling court filings, embassy document processing, certified translation pickups, and government office liaison across Germany and the EU.",
    skills: ["court filings", "embassy processing", "administrative liaison"],
    categories: ["Document & Legal", "Errands & Delivery"],
    location: "Berlin, DE",
    locationInfo: { city: "Berlin", region: "Berlin", country: "Germany", countryCode: "DE", continent: "Europe" },
    timezone: "UTC+1",
    hourlyRate: 70,
    flatRates: { "court filing": 95, "embassy document run": 75 },
    availability: "offline",
    responseTime: "< 6 hr",
    completions: 15,
    rating: 4.4,
    reputationScore: 420,
    reputationTier: "Bronze",
    verified: true,
    joinedAt: 1705000000000,
  },
  {
    id: "h10",
    name: "Daniel Nguyen",
    address: "0xb238...4E5C",
    avatar: "DN",
    bio: "FAA Part 107 certified drone operator providing aerial photography, orthomosaic mapping, property surveys, and real estate video production throughout the Pacific Northwest.",
    skills: ["aerial photography", "orthomosaic mapping", "property surveys"],
    categories: ["Photography & Video", "Field Research"],
    location: "Seattle, WA",
    locationInfo: { city: "Seattle", region: "Washington", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 200,
    flatRates: { "aerial survey": 350, "real estate video": 500 },
    availability: "available",
    responseTime: "< 3 hr",
    completions: 19,
    rating: 4.9,
    reputationScore: 580,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1703500000000,
  },
  {
    id: "h11",
    name: "Fatima Al-Rashid",
    address: "0xe593...82F1",
    avatar: "FA",
    bio: "UX research consultant specializing in physical product usability testing, in-store experience audits, and accessibility compliance assessments conducted in real-world environments.",
    skills: ["usability testing", "experience audits", "accessibility assessment"],
    categories: ["Testing & QA"],
    location: "Dubai, UAE",
    locationInfo: { city: "Dubai", region: "Dubai", country: "United Arab Emirates", countryCode: "AE", continent: "Asia" },
    timezone: "UTC+4",
    hourlyRate: 95,
    flatRates: { "usability test report": 160, "accessibility audit": 200 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 42,
    rating: 4.7,
    reputationScore: 710,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1700500000000,
  },
  {
    id: "h12",
    name: "Ryan Caldwell",
    address: "0x72d6...3B09",
    avatar: "RC",
    bio: "Smart home integration specialist and low-voltage electrician. IoT device provisioning, Z-Wave/Zigbee mesh setup, home automation wiring, and security system installation.",
    skills: ["IoT provisioning", "home automation", "security installation"],
    categories: ["Hardware & Setup"],
    location: "Denver, CO",
    locationInfo: { city: "Denver", region: "Colorado", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-7",
    hourlyRate: 100,
    flatRates: { "smart lock installation": 85, "full home automation": 650 },
    availability: "busy",
    responseTime: "< 4 hr",
    completions: 35,
    rating: 4.6,
    reputationScore: 640,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1701500000000,
  },
  {
    id: "h13",
    name: "Sophie Chen",
    address: "0xd4a8...0C7E",
    avatar: "SC",
    bio: "Personal concierge and errand management specialist in Toronto. Providing grocery procurement, retail returns processing, prescription coordination, and comparison shopping services.",
    skills: ["concierge services", "procurement", "returns processing"],
    categories: ["Errands & Delivery"],
    location: "Toronto, CA",
    locationInfo: { city: "Toronto", region: "Ontario", country: "Canada", countryCode: "CA", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 40,
    flatRates: { "grocery procurement": 35, "returns processing": 25 },
    availability: "available",
    responseTime: "< 20 min",
    completions: 78,
    rating: 4.8,
    reputationScore: 830,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1697000000000,
  },
  {
    id: "h14",
    name: "Arjun Mehta",
    address: "0xa1b5...6D42",
    avatar: "AM",
    bio: "Environmental monitoring technician conducting air quality measurements, water sampling, noise level assessments, and regulatory compliance inspections across Maharashtra.",
    skills: ["environmental monitoring", "compliance inspections", "sample collection"],
    categories: ["Field Research", "Other Physical"],
    location: "Mumbai, IN",
    locationInfo: { city: "Mumbai", region: "Maharashtra", country: "India", countryCode: "IN", continent: "Asia" },
    timezone: "UTC+5:30",
    hourlyRate: 45,
    flatRates: { "site inspection": 65, "environmental assessment": 90 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 26,
    rating: 4.5,
    reputationScore: 490,
    reputationTier: "Bronze",
    verified: false,
    joinedAt: 1704500000000,
  },
  {
    id: "h15",
    name: "Kasia Wojcik",
    address: "0xf3c9...8E1B",
    avatar: "KW",
    bio: "Event documentation specialist providing professional photography, multi-camera live streaming, and real-time social media coverage for conferences, product launches, and corporate events.",
    skills: ["event photography", "live streaming", "social media coverage"],
    categories: ["Photography & Video", "Meetings & Events"],
    location: "Warsaw, PL",
    locationInfo: { city: "Warsaw", region: "Masovia", country: "Poland", countryCode: "PL", continent: "Europe" },
    timezone: "UTC+1",
    hourlyRate: 85,
    flatRates: { "event coverage (half day)": 320, "live stream setup": 175 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 33,
    rating: 4.7,
    reputationScore: 660,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1702500000000,
  },
];
