import type { HumanProvider } from "./types";

export const MOCK_HUMANS: HumanProvider[] = [
  {
    id: "h1",
    name: "Alex Rivera",
    address: "0x1a2b...3c4d",
    avatar: "AR",
    bio: "Reliable courier in Austin. Same-day pickup and delivery for packages, documents, and small items. Bike and car available.",
    skills: ["package delivery", "same-day courier", "document pickup"],
    categories: ["Errands & Delivery"],
    location: "Austin, TX",
    locationInfo: { city: "Austin", region: "Texas", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-6",
    hourlyRate: 30,
    flatRates: { "package pickup": 25, "document delivery": 20 },
    availability: "available",
    responseTime: "< 15 min",
    completions: 47,
    rating: 4.9,
    reputationScore: 820,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1700000000000,
  },
  {
    id: "h2",
    name: "Maria Santos",
    address: "0x5e6f...7a8b",
    avatar: "MS",
    bio: "Licensed notary public in NYC. Mobile notarization services for legal documents, affidavits, and contracts.",
    skills: ["notarization", "legal documents", "affidavits", "contracts"],
    categories: ["Document & Legal"],
    location: "New York, NY",
    locationInfo: { city: "New York", region: "New York", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 120,
    flatRates: { "document notarization": 100, "contract witnessing": 80 },
    availability: "available",
    responseTime: "< 30 min",
    completions: 93,
    rating: 5.0,
    reputationScore: 950,
    reputationTier: "Platinum",
    verified: true,
    joinedAt: 1695000000000,
  },
  {
    id: "h3",
    name: "James Okafor",
    address: "0x9c0d...1e2f",
    avatar: "JO",
    bio: "Market researcher and data collector in London. Street-level surveys, competitor analysis, and on-site reporting.",
    skills: ["field surveys", "market research", "data collection"],
    categories: ["Field Research"],
    location: "London, UK",
    locationInfo: { city: "London", region: "England", country: "United Kingdom", countryCode: "GB", continent: "Europe" },
    timezone: "UTC+0",
    hourlyRate: 80,
    flatRates: { "store visit report": 60, "competitor survey": 120 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 31,
    rating: 4.7,
    reputationScore: 680,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1702000000000,
  },
  {
    id: "h4",
    name: "Priya Sharma",
    address: "0x3a4b...5c6d",
    avatar: "PS",
    bio: "Professional product photographer in LA. Studio and on-location shoots for e-commerce, social media, and catalogs.",
    skills: ["product photography", "studio lighting", "photo editing"],
    categories: ["Photography & Video"],
    location: "Los Angeles, CA",
    locationInfo: { city: "Los Angeles", region: "California", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 150,
    flatRates: { "product shoot (10 items)": 200, "lifestyle session": 300 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 64,
    rating: 4.8,
    reputationScore: 780,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1698000000000,
  },
  {
    id: "h5",
    name: "Tom Chen",
    address: "0x7e8f...9a0b",
    avatar: "TC",
    bio: "IT hardware specialist in SF. Server rack setup, network cabling, device installation, and troubleshooting.",
    skills: ["hardware setup", "network cabling", "server installation"],
    categories: ["Hardware & Setup"],
    location: "San Francisco, CA",
    locationInfo: { city: "San Francisco", region: "California", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 175,
    flatRates: { "server rack setup": 400, "network install": 150 },
    availability: "busy",
    responseTime: "< 4 hr",
    completions: 28,
    rating: 4.9,
    reputationScore: 720,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1701000000000,
  },
  {
    id: "h6",
    name: "Sarah Mitchell",
    address: "0xbc1d...2e3f",
    avatar: "SM",
    bio: "Professional meeting attendee in Chicago. Conference representation, note-taking, networking, and event reporting.",
    skills: ["meeting attendance", "note-taking", "networking", "event reporting"],
    categories: ["Meetings & Events"],
    location: "Chicago, IL",
    locationInfo: { city: "Chicago", region: "Illinois", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-6",
    hourlyRate: 75,
    flatRates: { "conference day pass": 400, "meeting representation": 75 },
    availability: "available",
    responseTime: "< 30 min",
    completions: 52,
    rating: 4.6,
    reputationScore: 690,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1699000000000,
  },
  {
    id: "h7",
    name: "Carlos Mendez",
    address: "0x4d5e...6f7a",
    avatar: "CM",
    bio: "Food and beverage tester in Miami. Taste testing, restaurant reviews, and quality assurance for food products.",
    skills: ["taste testing", "food review", "quality assurance"],
    categories: ["Testing & QA"],
    location: "Miami, FL",
    locationInfo: { city: "Miami", region: "Florida", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 50,
    flatRates: { "taste test session": 40, "restaurant review": 60 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 38,
    rating: 4.5,
    reputationScore: 550,
    reputationTier: "Silver",
    verified: false,
    joinedAt: 1703000000000,
  },
  {
    id: "h8",
    name: "Yuki Tanaka",
    address: "0x8b9c...0d1e",
    avatar: "YT",
    bio: "Event scout and venue researcher in Tokyo. Location scouting, event logistics, and cultural liaison services.",
    skills: ["event scouting", "venue research", "cultural liaison"],
    categories: ["Meetings & Events", "Field Research"],
    location: "Tokyo, JP",
    locationInfo: { city: "Tokyo", region: "Kanto", country: "Japan", countryCode: "JP", continent: "Asia" },
    timezone: "UTC+9",
    hourlyRate: 60,
    flatRates: { "venue scouting": 100, "event report": 80 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 21,
    rating: 4.8,
    reputationScore: 610,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1704000000000,
  },
  {
    id: "h9",
    name: "Elena Volkov",
    address: "0x2f3a...4b5c",
    avatar: "EV",
    bio: "Multilingual document runner in Berlin. Court filings, embassy visits, translation pickups, and government office errands.",
    skills: ["document filing", "embassy visits", "translation pickup"],
    categories: ["Document & Legal", "Errands & Delivery"],
    location: "Berlin, DE",
    locationInfo: { city: "Berlin", region: "Berlin", country: "Germany", countryCode: "DE", continent: "Europe" },
    timezone: "UTC+1",
    hourlyRate: 65,
    flatRates: { "court filing": 90, "embassy errand": 70 },
    availability: "offline",
    responseTime: "< 6 hr",
    completions: 15,
    rating: 4.4,
    reputationScore: 420,
    reputationTier: "Bronze",
    verified: true,
    joinedAt: 1705000000000,
  },
  {
    id: "h10",
    name: "David Park",
    address: "0x6c7d...8e9f",
    avatar: "DP",
    bio: "Drone operator and videographer in Seattle. Aerial photography, property surveys, and real estate video tours.",
    skills: ["drone operation", "aerial photography", "video tours"],
    categories: ["Photography & Video", "Field Research"],
    location: "Seattle, WA",
    locationInfo: { city: "Seattle", region: "Washington", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-8",
    hourlyRate: 200,
    flatRates: { "aerial survey": 350, "property video tour": 500 },
    availability: "available",
    responseTime: "< 3 hr",
    completions: 19,
    rating: 4.9,
    reputationScore: 580,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1703500000000,
  },
  {
    id: "h11",
    name: "Fatima Al-Hassan",
    address: "0xa0b1...c2d3",
    avatar: "FA",
    bio: "User testing specialist in Dubai. Physical product testing, UX walkthroughs, and accessibility audits in real environments.",
    skills: ["product testing", "UX testing", "accessibility audits"],
    categories: ["Testing & QA"],
    location: "Dubai, UAE",
    locationInfo: { city: "Dubai", region: "Dubai", country: "United Arab Emirates", countryCode: "AE", continent: "Asia" },
    timezone: "UTC+4",
    hourlyRate: 90,
    flatRates: { "product test report": 150, "UX walkthrough": 120 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 42,
    rating: 4.7,
    reputationScore: 710,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1700500000000,
  },
  {
    id: "h12",
    name: "Mike Johnson",
    address: "0xe4f5...6a7b",
    avatar: "MJ",
    bio: "Handyman and smart home installer in Denver. IoT device setup, smart lock installation, and home automation wiring.",
    skills: ["smart home setup", "IoT installation", "home automation"],
    categories: ["Hardware & Setup"],
    location: "Denver, CO",
    locationInfo: { city: "Denver", region: "Colorado", country: "United States", countryCode: "US", continent: "North America" },
    timezone: "UTC-7",
    hourlyRate: 100,
    flatRates: { "smart lock install": 80, "full home automation": 600 },
    availability: "busy",
    responseTime: "< 4 hr",
    completions: 35,
    rating: 4.6,
    reputationScore: 640,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1701500000000,
  },
  {
    id: "h13",
    name: "Lisa Wang",
    address: "0x8c9d...0e1f",
    avatar: "LW",
    bio: "Personal shopper and errand runner in Toronto. Grocery runs, returns, prescription pickups, and comparison shopping.",
    skills: ["personal shopping", "grocery runs", "returns processing"],
    categories: ["Errands & Delivery"],
    location: "Toronto, CA",
    locationInfo: { city: "Toronto", region: "Ontario", country: "Canada", countryCode: "CA", continent: "North America" },
    timezone: "UTC-5",
    hourlyRate: 35,
    flatRates: { "grocery run": 30, "return processing": 20 },
    availability: "available",
    responseTime: "< 20 min",
    completions: 78,
    rating: 4.8,
    reputationScore: 830,
    reputationTier: "Gold",
    verified: true,
    joinedAt: 1697000000000,
  },
  {
    id: "h14",
    name: "Raj Patel",
    address: "0x2a3b...4c5d",
    avatar: "RP",
    bio: "Environmental data collector in Mumbai. Air quality readings, water sampling, noise level measurements, and site inspections.",
    skills: ["environmental data", "site inspections", "sample collection"],
    categories: ["Field Research", "Other Physical"],
    location: "Mumbai, IN",
    locationInfo: { city: "Mumbai", region: "Maharashtra", country: "India", countryCode: "IN", continent: "Asia" },
    timezone: "UTC+5:30",
    hourlyRate: 45,
    flatRates: { "site inspection": 60, "data collection run": 40 },
    availability: "available",
    responseTime: "< 2 hr",
    completions: 26,
    rating: 4.5,
    reputationScore: 490,
    reputationTier: "Bronze",
    verified: false,
    joinedAt: 1704500000000,
  },
  {
    id: "h15",
    name: "Anna Kowalski",
    address: "0x6e7f...8a9b",
    avatar: "AK",
    bio: "Event photographer and live-streamer in Warsaw. Conferences, product launches, and real-time event documentation.",
    skills: ["event photography", "live streaming", "event documentation"],
    categories: ["Photography & Video", "Meetings & Events"],
    location: "Warsaw, PL",
    locationInfo: { city: "Warsaw", region: "Masovia", country: "Poland", countryCode: "PL", continent: "Europe" },
    timezone: "UTC+1",
    hourlyRate: 85,
    flatRates: { "event coverage (half day)": 300, "live stream setup": 150 },
    availability: "available",
    responseTime: "< 1 hr",
    completions: 33,
    rating: 4.7,
    reputationScore: 660,
    reputationTier: "Silver",
    verified: true,
    joinedAt: 1702500000000,
  },
];
