"use client";

import { useState, useEffect } from "react";
import { useAccount } from "wagmi";
import { motion } from "framer-motion";
import Link from "next/link";
import { Shield, Terminal, FileText, Scale, CheckCircle } from "lucide-react";
import { fadeUp } from "@/lib/motion";
import { TestResultCard } from "@/components/arbitrator/TestResultCard";

interface StatusResponse {
  certified: boolean;
  testTaken: boolean;
  passed?: boolean;
  score?: { mc: number; analysis: number; rulingCorrect: boolean };
  submittedAt?: number;
  txHash?: string | null;
}

export default function ArbitratorTestPage() {
  const { address, isConnected } = useAccount();
  const [status, setStatus] = useState<StatusResponse | null>(null);

  useEffect(() => {
    if (!isConnected || !address) return;
    fetch("/api/arbitrator/test/status", { credentials: "include" })
      .then((r) => r.json())
      .then((data: StatusResponse) => setStatus(data))
      .catch(() => {});
  }, [isConnected, address]);

  const isCertified = status?.certified || status?.passed;

  return (
    <div className="mx-auto max-w-3xl px-4 py-10">
      <motion.div {...fadeUp} className="space-y-6">
        {/* Header */}
        <div className="text-center">
          <Shield className="mx-auto mb-4 h-12 w-12 text-orange-400" />
          <h1 className="mb-2 text-2xl font-bold text-white">
            Arbitrator Competency Test
          </h1>
          <p className="text-sm text-white/60">
            Prove your ability to analyze evidence and make fair rulings.
            Each test is uniquely generated by AI — no two tests are the same.
          </p>
        </div>

        {/* Certified banner */}
        {isCertified && status?.score && (
          <div className="rounded-lg border border-green-500/30 bg-green-500/5 p-6 text-center">
            <CheckCircle className="mx-auto mb-3 h-10 w-10 text-green-400" />
            <h2 className="mb-1 text-lg font-bold text-green-400">
              Certified Arbitrator
            </h2>
            <p className="mb-4 text-sm text-white/60">
              You passed the competency test and are eligible for dispute panel selection.
            </p>
            <div className="mx-auto max-w-xs">
              <TestResultCard
                passed={true}
                scores={status.score}
                txHash={status.txHash}
              />
            </div>
          </div>
        )}

        {/* How it works */}
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-white">How It Works</h2>

          <div className="grid gap-3">
            <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/5 p-4">
              <FileText className="mt-0.5 h-5 w-5 shrink-0 text-orange-400" />
              <div>
                <p className="text-sm font-medium text-white/90">
                  1. Evidence Review
                </p>
                <p className="text-xs text-white/50">
                  AI generates a unique dispute scenario with contracts, chat logs, and records.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/5 p-4">
              <FileText className="mt-0.5 h-5 w-5 shrink-0 text-orange-400" />
              <div>
                <p className="text-sm font-medium text-white/90">
                  2. Multiple Choice (80% to pass)
                </p>
                <p className="text-xs text-white/50">
                  5 questions testing your comprehension of the evidence.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/5 p-4">
              <FileText className="mt-0.5 h-5 w-5 shrink-0 text-orange-400" />
              <div>
                <p className="text-sm font-medium text-white/90">
                  3. Written Analysis (70% to pass)
                </p>
                <p className="text-xs text-white/50">
                  Write your analysis of the dispute. Graded by AI against a rubric.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/5 p-4">
              <Scale className="mt-0.5 h-5 w-5 shrink-0 text-orange-400" />
              <div>
                <p className="text-sm font-medium text-white/90">
                  4. Mock Ruling (must be correct)
                </p>
                <p className="text-xs text-white/50">
                  Cast your ruling — BuyerWins or SellerWins.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* CLI instruction */}
        <div className="rounded-lg border border-orange-500/30 bg-orange-500/5 p-6">
          <div className="flex items-start gap-3">
            <Terminal className="mt-0.5 h-6 w-6 shrink-0 text-orange-400" />
            <div>
              <h3 className="mb-1 text-sm font-bold text-orange-400">
                Take the Test via CLI
              </h3>
              <p className="mb-3 text-sm text-white/60">
                The certification test runs entirely through the LOBSTR CLI.
                Make sure you have a registered wallet and forum account.
              </p>
              <div className="rounded-md bg-black/40 px-4 py-3 font-mono text-sm text-white/80">
                lobstr arbitrate test
              </div>
              <p className="mt-2 text-xs text-white/40">
                The test takes about 5-10 minutes. Each attempt generates a unique scenario.
                Pass all 3 sections to get certified on-chain.
              </p>
            </div>
          </div>
        </div>

        {/* Nav links */}
        <div className="flex gap-3">
          <Link
            href="/disputes"
            className="flex-1 rounded-lg border border-white/10 px-4 py-2.5 text-center text-sm text-white/60 hover:border-white/20 hover:text-white/80"
          >
            View Disputes
          </Link>
          <Link
            href="/"
            className="flex-1 rounded-lg border border-white/10 px-4 py-2.5 text-center text-sm text-white/60 hover:border-white/20 hover:text-white/80"
          >
            Back to Home
          </Link>
        </div>
      </motion.div>
    </div>
  );
}
